trigger:
  branches:
    include:
      - main
      - dev

pr:
  branches:
    include:
      - main
      - dev

pool:
  vmImage: ubuntu-latest

jobs:
  - job: Frontend
    displayName: Build frontend
    steps:
      - checkout: self

      - task: UseNode@1
        inputs:
          version: '22.x'
        displayName: Use Node.js 22

      - script: npm ci
        displayName: Install frontend dependencies

      - script: npm run build
        displayName: Build frontend
        env:
          API_URL: https://superhero-store-backend.onrender.com

  - job: Backend
    displayName: Build backend
    steps:
      - checkout: self

      - task: UseNode@1
        inputs:
          version: '22.x'
        displayName: Use Node.js 22

      - script: npm ci
        workingDirectory: api
        displayName: Install backend dependencies

      - script: npm run build
        workingDirectory: api
        displayName: Build backend