import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Toaster } from "react-hot-toast";
import { ToastListener } from "@/components/toast-listener";
import { Providers } from "@/lib/providers";
import CartProviderWrapper from "@/components/ui/cart-provider-wrapper";

const inter = Inter({
	subsets: ["latin"],
	weight: ["400", "600", "700"],
	variable: "--font-inter",
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className={`${inter.variable} antialiased `}>
				<Toaster position="top-center" />
				<ToastListener />
				<CartProviderWrapper>
					<Providers>{children}</Providers>
				</CartProviderWrapper>
			</body>
		</html>
	);
}
